# Generated by Django 3.2.11 on 2022-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('reply_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('replied_date', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
